### ISSUE TITLE
无论我怎么使用，哪怕是使用测试数据，他总会报错

### ISSUE THREAD

**Issue by fuhudalong** [FreeGIS/dem2terrain#11]
C:\Users\14443\Downloads>dem2terrain -z 4-10 -e terrarium -i test.tif -o D:\BaiduNetdiskDownload\tile.mbtiles  -g 4326

>> 开始转换...
- 输入文件: C:\Users\14443\Downloads\test.tif
- 输出路径: D:\BaiduNetdiskDownload\tile.mbtiles
- Tile适用坐标系: EPSG:4326
- 瓦片编码: terrarium
- 瓦片尺寸: 256 px
- 瓦片等级: 4 至 10 级

>> 步骤1: 重投影至 EPSG:4326 - 完成
>> 步骤2: 构建影像金字塔索引 - 完成
>> 步骤3: 完成 - 100.00% ████████████████████████████████████████████████████████████ 37/37C:\Users\14443\AppData\Roaming\npm\node_modules\dem2terrain\src\mbtiles-util.js:10
                mbtiles.startWriting(function (err) {
                        ^

TypeError: Cannot read properties of undefined (reading 'startWriting')
    at C:\Users\14443\AppData\Roaming\npm\node_modules\dem2terrain\src\mbtiles-util.js:10:25
    at Database.<anonymous> (C:\Users\14443\AppData\Roaming\npm\node_modules\dem2terrain\node_modules\@mapbox\mbtiles\lib\mbtiles.js:81:25)

Node.js v20.17.0

**Comment by FreeGIS** [comment]
该问题是@mapbox/mbtiles安装异常，该库依赖sqlite，可能本机环境存在多个sqlite等导致环境紊乱。
