### ISSUE TITLE
运行报错  node20.16.0

### ISSUE THREAD

**Issue by ShareQiu1994** [FreeGIS/dem2terrain#14]
>> 开始转换...
- 输入文件: D:\code\dem2terrain\test\dem.tif
- 输出路径: D:\code\dem2terrain\test\terrain
- Tile适用坐标系: EPSG:3857
- 瓦片编码: mapbox(raster-dem)
- 瓦片尺寸: 512 px
- 瓦片等级: 5 至 13 级

>> 步骤1: 清空输出文件夹 - 完成
D:\code\dem2terrain\src
D:\code\dem2terrain\src\gdal-util.js:37
  const t_srs = gdal.SpatialReference.fromEPSGA(t_epsg);
                                      ^

Error: PROJ: proj_create_from_database: Cannot find proj.db
    at reprojectImage (D:\code\dem2terrain\src\gdal-util.js:37:39)
    at project (D:\code\dem2terrain\src\index.js:173:3)
    at main (D:\code\dem2terrain\src\index.js:268:19)
    at Object.<anonymous> (D:\code\dem2terrain\bin\dem2terrain.js:76:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

**Comment by FreeGIS** [comment]
> > > 开始转换...
> 
> * 输入文件: D:\code\dem2terrain\test\dem.tif
> * 输出路径: D:\code\dem2terrain\test\terrain
> * Tile适用坐标系: EPSG:3857
> * 瓦片编码: mapbox(raster-dem)
> * 瓦片尺寸: 512 px
> * 瓦片等级: 5 至 13 级
> 
> > > 步骤1: 清空输出文件夹 - 完成
> > > D:\code\dem2terrain\src
> > > D:\code\dem2terrain\src\gdal-util.js:37
> > > const t_srs = gdal.SpatialReference.fromEPSGA(t_epsg);
> > > ^
> 
> Error: PROJ: proj_create_from_database: Cannot find proj.db at reprojectImage (D:\code\dem2terrain\src\gdal-util.js:37:39) at project (D:\code\dem2terrain\src\index.js:173:3) at main (D:\code\dem2terrain\src\index.js:268:19) at Object. (D:\code\dem2terrain\bin\dem2terrain.js:76:1) at Module._compile (node:internal/modules/cjs/loader:1358:14) at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) at Module.load (node:internal/modules/cjs/loader:1208:32) at Module._load (node:internal/modules/cjs/loader:1024:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) at node:internal/main/run_main_module:28:49

原因是gdal环境问题，gdal依赖proj，proj有个sqlite的元数据库即proj.db。 有时候，可能机器上有多套proj环境，例如在windows机器上，当你安装PostGIS会安装proj.db，当安装gdal又会装，环境乱了会出现找不到的问题。

具体参考readme的 5.2 环境变量冲突 相关内容
